### ISSUE TITLE
Undefined behavior when user has no permmisions to guest's Cibus

### ISSUE THREAD

**Issue by guylapid** [amitmarx/pimp-my-wolt#11]
When some guest did not provide Cibus permissions to the user performing the order, then when arriving at the Cibus order page, this guest doesn't appear in the user's list of available Cibus guests.
This causes this piece of code:
```js
const cibusName = guests.find(
  (guest) => guest.woltName === guestOrder.name
)?.cibusName;
```
in `handleCibusPayment` to return `undefined`.
It causes an incorrect debt division among the rest of the guests.

I think a good behavior would be to show some red warning label such as "You don't have permissions to Cibus for some of the guests: Moshe Cohen, Ploni Almoni", and cancel the automatic division.
I guess anyway in this case the user would want to go talk to the person who didn't give them permissions, and refresh the order page so that the new guest would appear, so there is no point in continuing...

What do you think?
I can open a PR with these changes if you are cool with that.

**Comment by amitmarx** [comment]
Hey,
Sorry for a huge delay, I missed your post.
I think warning is great, so as you said, no one will mistakenly send the order with a wrong split.
But I don't think it should cancel the devision, as a user may suggest to pay for someone and ask for return.
In my company, this is what we typically do, as otherwise we will be required to create the entire order from scratch.

So, if you're up for creating a PR for the warning, I'll be happy to push it :)
